export type CardColor = "Blue" | "Green" | "Red" | "White" | "Purple" | "-";

export type CardType =
  | "UNIT"
  | "PILOT"
  | "COMMAND"
  | "BASE"
  | "RESOURCE"
  | "EX RESOURCE";

export type GundamCard = {
  number: string;
  name: string;
  rarity: string;
  level: string;
  cost: string;
  color: CardColor;
  type: CardType;
  text: string;
  trait: string;
  link: string;
  ap: string;
  hp: string;
  source: string;
  set: string;
};

export const CARD_POOL: GundamCard[] = [
  {
    number: "ST01-001",
    name: "Gundam",
    rarity: "LR",
    level: "4",
    cost: "3",
    color: "Blue",
    type: "UNIT",
    text: "<Repair 2>. During pair, all your Units get AP+1 during your turn.",
    trait: "(Earth Federation) (White Base Team)",
    link: "[Amuro Ray]",
    ap: "3",
    hp: "4",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-002",
    name: "Gundam (MA Form)",
    rarity: "C",
    level: "5",
    cost: "3",
    color: "Blue",
    type: "UNIT",
    text: "When paired with a White Base Team pilot, draw 1.",
    trait: "(Earth Federation) (White Base Team)",
    link: "[Amuro Ray]",
    ap: "4",
    hp: "3",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-003",
    name: "Guncannon",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "Blue",
    type: "UNIT",
    text: "-",
    trait: "(Earth Federation) (White Base Team)",
    link: "[Kai Shiden]",
    ap: "2",
    hp: "4",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-004",
    name: "Guntank",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "Blue",
    type: "UNIT",
    text: "Deploy: choose 1 enemy Unit with 2 or less HP and rest it.",
    trait: "(Earth Federation) (White Base Team)",
    link: "[Hayato Kobayashi]",
    ap: "2",
    hp: "3",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-005",
    name: "GM",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "Blue",
    type: "UNIT",
    text: "-",
    trait: "(Earth Federation)",
    link: "-",
    ap: "2",
    hp: "2",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-006",
    name: "Gundam Aerial (Permet Score Six)",
    rarity: "LR",
    level: "5",
    cost: "4",
    color: "White",
    type: "UNIT",
    text: "When paired, choose 1 Lv.5 or lower enemy Unit. It gets AP-3 this turn.",
    trait: "(Academy)",
    link: "[Suletta Mercury]",
    ap: "4",
    hp: "4",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-007",
    name: "Gundam Aerial (Bit on Form)",
    rarity: "C",
    level: "4",
    cost: "2",
    color: "White",
    type: "UNIT",
    text: "-",
    trait: "(Academy)",
    link: "[Suletta Mercury]",
    ap: "3",
    hp: "4",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-008",
    name: "Demi Trainer",
    rarity: "C",
    level: "1",
    cost: "1",
    color: "White",
    type: "UNIT",
    text: "<Blocker>.",
    trait: "(Academy)",
    link: "-",
    ap: "1",
    hp: "1",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-009",
    name: "Zowort",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "White",
    type: "UNIT",
    text: "<Blocker>. This Unit cannot choose the enemy player as its attack target.",
    trait: "(Academy)",
    link: "-",
    ap: "3",
    hp: "2",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-010",
    name: "Amuro Ray",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "Blue",
    type: "PILOT",
    text: "Burst: add this card to your hand. When paired, rest 1 enemy Unit with 5 or less HP.",
    trait: "(Earth Federation) (White Base Team) (Newtype)",
    link: "-",
    ap: "+2",
    hp: "+1",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-011",
    name: "Suletta Mercury",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "White",
    type: "PILOT",
    text: "Burst: add this card to your hand. Attack once per turn: ready 1 of your Resources.",
    trait: "(Academy)",
    link: "-",
    ap: "+1",
    hp: "+2",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-012",
    name: "Thoroughly Damaged",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "Blue",
    type: "COMMAND",
    text: "Main: deal 1 damage to 1 rested enemy Unit. Pilot: Hayato Kobayashi.",
    trait: "(Earth Federation) (White Base Team)",
    link: "-",
    ap: "+0",
    hp: "+1",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-013",
    name: "Kai's Resolve",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "Blue",
    type: "COMMAND",
    text: "Main: choose 1 friendly Unit. It recovers 3 HP. Pilot: Kai Shiden.",
    trait: "(Earth Federation) (White Base Team)",
    link: "-",
    ap: "+1",
    hp: "+0",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-014",
    name: "Unforeseen Incident",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "White",
    type: "COMMAND",
    text: "Burst/Main/Action: choose 1 enemy Unit. It gets AP-3 this turn.",
    trait: "-",
    link: "-",
    ap: "-",
    hp: "-",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-015",
    name: "White Base",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "Blue",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand. Main: deploy a White Base Team Unit token.",
    trait: "(Earth Federation) (White Base Team) (Warship)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST01-016",
    name: "Asticassia School of Technology, Earth House",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "White",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand. Main: rest this Base to give friendly Link Units AP+1.",
    trait: "(Academy) (Stronghold)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam the Witch from Mercury",
    set: "Heroic Beginnings [ST01]",
  },
  {
    number: "ST02-001",
    name: "Wing Gundam",
    rarity: "LR",
    level: "6",
    cost: "4",
    color: "Green",
    type: "UNIT",
    text: "<Breach 5>. May attack active enemy Units that are Lv.4 or lower.",
    trait: "(Operation Meteor)",
    link: "[Heero Yuy]",
    ap: "4",
    hp: "5",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-002",
    name: "Wing Gundam (Bird Mode)",
    rarity: "C",
    level: "3",
    cost: "3",
    color: "Green",
    type: "UNIT",
    text: "Deploy: place 1 EX Resource.",
    trait: "(Operation Meteor)",
    link: "[Heero Yuy]",
    ap: "2",
    hp: "2",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-003",
    name: "Gundam Heavyarms",
    rarity: "C",
    level: "5",
    cost: "3",
    color: "Green",
    type: "UNIT",
    text: "During pair, when this destroys an enemy Unit with battle damage, deal 1 to all enemy Units Lv.3 or lower.",
    trait: "(Operation Meteor)",
    link: "[Trowa Barton]",
    ap: "3",
    hp: "4",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-004",
    name: "Gundam Sandrock",
    rarity: "C",
    level: "4",
    cost: "2",
    color: "Green",
    type: "UNIT",
    text: "-",
    trait: "(Operation Meteor)",
    link: "[Quatre Raberba Winner]",
    ap: "4",
    hp: "3",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-005",
    name: "Maganac",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Green",
    type: "UNIT",
    text: "-",
    trait: "(Maganac Corps)",
    link: "-",
    ap: "3",
    hp: "2",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-006",
    name: "Tallgeese",
    rarity: "LR",
    level: "5",
    cost: "4",
    color: "Blue",
    type: "UNIT",
    text: "Main once per turn: pay 4 to set this Unit as active.",
    trait: "(OZ)",
    link: "[Zechs Merquise]",
    ap: "4",
    hp: "4",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-007",
    name: "Leo",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Blue",
    type: "UNIT",
    text: "-",
    trait: "(OZ)",
    link: "(OZ) Trait",
    ap: "2",
    hp: "2",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-008",
    name: "Aries",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Blue",
    type: "UNIT",
    text: "<Blocker>.",
    trait: "(OZ)",
    link: "-",
    ap: "2",
    hp: "1",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-009",
    name: "Tragos",
    rarity: "C",
    level: "1",
    cost: "1",
    color: "Blue",
    type: "UNIT",
    text: "<Blocker>.",
    trait: "(OZ)",
    link: "-",
    ap: "1",
    hp: "1",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-010",
    name: "Heero Yuy",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "Green",
    type: "PILOT",
    text: "Burst: add this card to your hand. During link, this Unit gets AP+1 and HP+1.",
    trait: "(Operation Meteor)",
    link: "-",
    ap: "+2",
    hp: "+1",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-011",
    name: "Zechs Merquise",
    rarity: "C",
    level: "5",
    cost: "1",
    color: "Blue",
    type: "PILOT",
    text: "Burst: add this card to your hand. During link, draw 1 when this Unit destroys an enemy Unit with battle damage.",
    trait: "(OZ)",
    link: "-",
    ap: "+2",
    hp: "+1",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-012",
    name: "Simultaneous Fire",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "Green",
    type: "COMMAND",
    text: "Main: 1 of your Units gains <Breach 3>. Pilot: Trowa Barton.",
    trait: "(Operation Meteor)",
    link: "-",
    ap: "+1",
    hp: "+1",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-013",
    name: "Peaceful Timbre",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "Green",
    type: "COMMAND",
    text: "Action: shields cannot receive damage from enemy Units Lv.4 or lower in this battle. Pilot: Quatre.",
    trait: "(Operation Meteor)",
    link: "-",
    ap: "+1",
    hp: "+1",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-014",
    name: "Siege Ploy",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "Blue",
    type: "COMMAND",
    text: "Burst/Main/Action: rest 1 enemy Unit with 5 or less HP.",
    trait: "-",
    link: "-",
    ap: "-",
    hp: "-",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-015",
    name: "Saint Gabriel Institute",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Green",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand, then smooth the top 2 cards of your deck.",
    trait: "(Academy) (Stronghold)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST02-016",
    name: "Corsica Base",
    rarity: "C",
    level: "3",
    cost: "3",
    color: "Blue",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand, then deploy Tallgeese or Leo Unit tokens.",
    trait: "(OZ) (Stronghold)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam Wing",
    set: "Wings of Advance [ST02]",
  },
  {
    number: "ST03-001",
    name: "Sinanju",
    rarity: "LR",
    level: "6",
    cost: "5",
    color: "Red",
    type: "UNIT",
    text: "During pair, gains <High-Maneuver>. When it destroys a shield with battle damage, deal 2 to 1 enemy Unit.",
    trait: "(Neo Zeon)",
    link: "[Full Frontal]",
    ap: "5",
    hp: "4",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-002",
    name: "Angelo's Geara Zulu",
    rarity: "C",
    level: "4",
    cost: "3",
    color: "Red",
    type: "UNIT",
    text: "Main: <Support 2>.",
    trait: "(Neo Zeon)",
    link: "[Angelo Sauper]",
    ap: "3",
    hp: "3",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-003",
    name: "Geara Zulu",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "Red",
    type: "UNIT",
    text: "-",
    trait: "(Neo Zeon)",
    link: "(Neo Zeon) Trait",
    ap: "3",
    hp: "2",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-004",
    name: "Gaza D (Sleeves)",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Red",
    type: "UNIT",
    text: "Main: <Support 2>.",
    trait: "(Neo Zeon)",
    link: "-",
    ap: "2",
    hp: "1",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-005",
    name: "Dra-C (Sleeves)",
    rarity: "C",
    level: "1",
    cost: "1",
    color: "Red",
    type: "UNIT",
    text: "-",
    trait: "(Neo Zeon)",
    link: "-",
    ap: "1",
    hp: "2",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-006",
    name: "Char's Zaku II",
    rarity: "LR",
    level: "3",
    cost: "2",
    color: "Green",
    type: "UNIT",
    text: "Destroyed: look at top 3, reveal a Zeon/Neo Zeon Unit, add it to your hand.",
    trait: "(Zeon)",
    link: "[Char Aznable]",
    ap: "3",
    hp: "2",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-007",
    name: "Zaku I",
    rarity: "C",
    level: "1",
    cost: "1",
    color: "Green",
    type: "UNIT",
    text: "-",
    trait: "(Zeon)",
    link: "-",
    ap: "1",
    hp: "2",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-008",
    name: "Zaku II",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "Green",
    type: "UNIT",
    text: "Attack: this Unit gets AP+2 this turn.",
    trait: "(Zeon)",
    link: "-",
    ap: "1",
    hp: "2",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-009",
    name: "Gouf",
    rarity: "C",
    level: "3",
    cost: "3",
    color: "Green",
    type: "UNIT",
    text: "Deploy: deploy 1 rested Zaku II Unit token.",
    trait: "(Zeon)",
    link: "[Ramba Ral]",
    ap: "2",
    hp: "3",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-010",
    name: "Full Frontal",
    rarity: "C",
    level: "6",
    cost: "1",
    color: "Red",
    type: "PILOT",
    text: "Burst: add this card to your hand. When paired, deploy a Lv.4 or lower Neo Zeon/Zeon Unit from hand.",
    trait: "(Neo Zeon) (Cyber-Newtype)",
    link: "-",
    ap: "+2",
    hp: "+2",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-011",
    name: "Char Aznable",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "Green",
    type: "PILOT",
    text: "Burst: add this card to your hand. Attack: AP+1 this turn and gains <High-Maneuver> if linked.",
    trait: "(Zeon) (Newtype)",
    link: "-",
    ap: "+1",
    hp: "+1",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-012",
    name: "Indignation",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "Red",
    type: "COMMAND",
    text: "Main/Action: 1 friendly Unit gets AP+2 this turn. Pilot: Angelo Sauper.",
    trait: "(Neo Zeon)",
    link: "-",
    ap: "+1",
    hp: "+0",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-013",
    name: "Close Combat",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Red",
    type: "COMMAND",
    text: "Burst/Main/Action: deal 2 damage to 1 enemy Unit.",
    trait: "-",
    link: "-",
    ap: "-",
    hp: "-",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-014",
    name: "The Blue Giant",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "Green",
    type: "COMMAND",
    text: "Action: 1 friendly Unit cannot receive battle damage from enemy Units with 2 or less AP. Pilot: Ramba Ral.",
    trait: "(Zeon)",
    link: "-",
    ap: "+1",
    hp: "+1",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-015",
    name: "Rewloola",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "Red",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand, then deal 1 damage to 1 enemy Unit with 5 or less AP.",
    trait: "(Neo Zeon) (Warship)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam Unicorn",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST03-016",
    name: "Falmel",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "Green",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand, then deploy a rested Char's Zaku II Unit token.",
    trait: "(Zeon) (Warship)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam",
    set: "Zeon's Rush [ST03]",
  },
  {
    number: "ST04-001",
    name: "Aile Strike Gundam",
    rarity: "LR",
    level: "5",
    cost: "4",
    color: "White",
    type: "UNIT",
    text: "<Blocker>. When paired with a Lv.4 or higher pilot, return 1 enemy Unit with 4 or less HP to hand.",
    trait: "(Earth Alliance)",
    link: "[Kira Yamato]",
    ap: "4",
    hp: "4",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-002",
    name: "Strike Gundam",
    rarity: "C",
    level: "4",
    cost: "2",
    color: "White",
    type: "UNIT",
    text: "Deploy: draw 1, then discard 1.",
    trait: "(Earth Alliance)",
    link: "[Kira Yamato]",
    ap: "3",
    hp: "3",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-003",
    name: "Moebius Zero",
    rarity: "C",
    level: "3",
    cost: "2",
    color: "White",
    type: "UNIT",
    text: "-",
    trait: "(Earth Alliance)",
    link: "[Mu La Flaga]",
    ap: "2",
    hp: "4",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-004",
    name: "Moebius",
    rarity: "C",
    level: "1",
    cost: "1",
    color: "White",
    type: "UNIT",
    text: "<Blocker>.",
    trait: "(Earth Alliance)",
    link: "-",
    ap: "1",
    hp: "1",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-005",
    name: "Strike Dagger",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "White",
    type: "UNIT",
    text: "-",
    trait: "(Earth Alliance)",
    link: "-",
    ap: "3",
    hp: "2",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-006",
    name: "Aegis Gundam",
    rarity: "LR",
    level: "4",
    cost: "3",
    color: "Red",
    type: "UNIT",
    text: "Attack: if this Unit has 5 or more AP, deal 3 damage to 1 Lv.5 or higher enemy Unit.",
    trait: "(ZAFT)",
    link: "[Athrun Zala]",
    ap: "4",
    hp: "3",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-007",
    name: "Aegis Gundam (MA Mode)",
    rarity: "C",
    level: "4",
    cost: "3",
    color: "Red",
    type: "UNIT",
    text: "<Breach 3>.",
    trait: "(ZAFT)",
    link: "[Athrun Zala]",
    ap: "3",
    hp: "4",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-008",
    name: "Ginn",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "Red",
    type: "UNIT",
    text: "-",
    trait: "(ZAFT)",
    link: "-",
    ap: "2",
    hp: "2",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-009",
    name: "Miguel's Ginn",
    rarity: "C",
    level: "2",
    cost: "2",
    color: "Red",
    type: "UNIT",
    text: "During pair/destroyed: draw 1 if you have another Link Unit in play.",
    trait: "(ZAFT)",
    link: "[Miguel Ayman]",
    ap: "3",
    hp: "1",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-010",
    name: "Kira Yamato",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "White",
    type: "PILOT",
    text: "Burst: add this card to your hand. Attack: choose 1 enemy Unit. It gets AP-2 this battle.",
    trait: "(Earth Alliance) (Coordinator)",
    link: "-",
    ap: "+2",
    hp: "+1",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-011",
    name: "Athrun Zala",
    rarity: "C",
    level: "4",
    cost: "1",
    color: "Red",
    type: "PILOT",
    text: "Burst: add this card to your hand. When linked, may attack active enemy Units Lv.5 or lower this turn.",
    trait: "(ZAFT) (Coordinator)",
    link: "-",
    ap: "+1",
    hp: "+2",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-012",
    name: "Striker Pack",
    rarity: "C",
    level: "4",
    cost: "2",
    color: "White",
    type: "COMMAND",
    text: "Burst/Main: deploy a Strike Gundam Unit token if you have no Earth Alliance Unit tokens.",
    trait: "-",
    link: "-",
    ap: "-",
    hp: "-",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-013",
    name: "Hawk of Endymion",
    rarity: "C",
    level: "2",
    cost: "1",
    color: "White",
    type: "COMMAND",
    text: "Main/Action: return 1 enemy Unit with 3 or less HP to hand. Pilot: Mu La Flaga.",
    trait: "(Earth Alliance)",
    link: "-",
    ap: "+1",
    hp: "+0",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-014",
    name: "The Magic Bullet of Dusk",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "Red",
    type: "COMMAND",
    text: "Main/Action: a Lv.2 or lower friendly Unit gains <First Strike>. Pilot: Miguel Ayman.",
    trait: "(ZAFT) (Coordinator)",
    link: "-",
    ap: "+0",
    hp: "+1",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-015",
    name: "Archangel",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "White",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand. Main once per turn: ready a friendly Unit with <Blocker>.",
    trait: "(Earth Alliance) (Warship)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "ST04-016",
    name: "Vesalius",
    rarity: "C",
    level: "3",
    cost: "1",
    color: "Red",
    type: "BASE",
    text: "Burst/deploy: add 1 Shield to your hand. Main: rest this Base to give 1 friendly Unit AP+1 this turn.",
    trait: "(ZAFT) (Warship)",
    link: "-",
    ap: "-",
    hp: "5",
    source: "Mobile Suit Gundam SEED",
    set: "SEED Strike [ST04]",
  },
  {
    number: "R-001",
    name: "Resource",
    rarity: "C",
    level: "-",
    cost: "-",
    color: "-",
    type: "RESOURCE",
    text: "Rest a Resource when paying a cost.",
    trait: "-",
    link: "-",
    ap: "-",
    hp: "-",
    source: "-",
    set: "Included in Starter Decks",
  },
  {
    number: "EXR-001",
    name: "EX Resource",
    rarity: "C",
    level: "-",
    cost: "-",
    color: "-",
    type: "EX RESOURCE",
    text: "Second-turn player starts with an active EX Resource; remove it when paying a cost.",
    trait: "-",
    link: "-",
    ap: "-",
    hp: "-",
    source: "-",
    set: "Included in Booster Packs",
  },
];
