// Generated by TCGplayer market sync on 2026-08-27T12:48:56.918Z.
import type { GundamCard } from "./card-data";

export const TCGPLAYER_CARD_POOL: GundamCard[] = [];
export const MARKET_CARD_POOL = TCGPLAYER_CARD_POOL;
