// Generated by TCGplayer market sync on 2026-08-19T09:28:45.073Z.
import type { GundamCard } from "./card-data";

export const TCGPLAYER_CARD_POOL: GundamCard[] = [];
export const MARKET_CARD_POOL = TCGPLAYER_CARD_POOL;
