// Generated by TCGplayer market sync on 2026-10-02T09:32:45.929Z.
import type { GundamCard } from "./card-data";

export const TCGPLAYER_CARD_POOL: GundamCard[] = [];
export const MARKET_CARD_POOL = TCGPLAYER_CARD_POOL;
