// Generated by TCGplayer market sync on 2026-09-07T09:36:08.636Z.
export const MARKET_LAST_SYNC: string | null = "2026-09-07T09:36:08.636Z";
export const TCGPLAYER_LAST_SYNC: string | null = MARKET_LAST_SYNC;
export const TCGPLAYER_CATEGORY_ID: number | null = 86;
