// Generated by TCGplayer market sync on 2026-09-20T09:26:40.038Z.
export const MARKET_LAST_SYNC: string | null = "2026-09-20T09:26:40.038Z";
export const TCGPLAYER_LAST_SYNC: string | null = MARKET_LAST_SYNC;
export const TCGPLAYER_CATEGORY_ID: number | null = 86;
